---
title: "nsf-rockfish-parentage"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: 
  github_document:
    toc: true
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, echo = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "readme-figs/"
)
```

This is an Rstudio project housing our analyses of parentage (and sibling inference)
of rockfish using our GTseq data off the MiSeq.

The full genotype data don't live in this repo, since that would be too much
for GitHub, but, the code for the early data processing steps is set up as if
you have them in a directory called `extdata` in this repository.  The `data` directory
here holds the meta data information for the individuals, and the plate maps that 
we use to associate the IDs from the genotyping data with all the metadata.


## Data Files

Check out `./R-main/01-compile-and-tidy-data.R` to see what we went through to tidy data up into a reasonably 
good long format.

Those steps produce these key files. The first two are part of this repository on GitHub.  The third is not, at the
present time.

1. `./data/meta-data-tibble.rds` an xz-compressed tibble of all the meta data from the SWFSC tissue repository. Open it in R with `readRDS()`.
2. `./data/sample-sheet-tibble.rds` an xz-compressed tibble of all the sample sheet information.  This lets us associate `gtseq_run` number and 
genotyping `id` with a `NMFS_DNA_ID` so we can associate meta-data with the genotyped individuals.
3. `./extdata/processed/called_genos.rds` an xz-compressed tibble of all the called genotypes in a long format.  Individuals are
identified by the `gtseq_run` and `id`, which can be used to get back to their `NMFS_DNA_ID`.  
4. `./extdata/processed/called_genos_na_explicit.rds` an xz-compressed tibble of all the genotypes in long format.  This one has explicitly put
NAs in for every individual listed in the sample sheet (in the previous file, individuals with no genotypes scored at all don't appear!).  It also 
includes the `NMFS_DNA_ID`.  This is the one to work from.  

All subsequent analyses start from these files.  


## Early maneuvers. Data Checking, etc.


1. First things first, verify who it is we have (and have not) genotyped, etc.  This is just a general overview
of the data.  R-markdown notebook: `./Rmd/general-data-overview.Rmd`
1. Check re-genotyped individuals for genotype concordance.



